### ISSUE TITLE
add support for Quilt client chrashes 

### ISSUE THREAD

**Issue by Dobby-progam** [aternosorg/codex-minecraft#49]
`Is Modded: Definitely; Client brand changed to 'quilt'`
you can see it here in a crash report, 
but it might be smart to set it to detect what is between the  '' so new issues like this won't need to be opened anymore

**Comment by JulianVennen** [comment]
We detect specific crash reports, we won't just show anything that someone puts as the client brand.

**Comment by JulianVennen** [comment]
Solved in 2.9.0
