### ISSUE TITLE
update CustomSkinLoader 

### ISSUE THREAD

**Issue by SerinaNya** [aternosorg/codex-minecraft#67]
https://github.com/aternosorg/codex-minecraft/blob/278a8b82ba06e74a1a0aa835091d14aaafb9ed00/src/Log/Minecraft/CustomSkinLoader/CustomSkinLoaderClientLog.php#L18

CustomSkinLoader is a long-established mod with numerous versions.  The log format is not exactly the same for each version.

I dont use PHP, it's hard to create a PR. Here's all I can do. 👇

---

Typical formats of CustomSkinLoader log:

```
[2020-04-28 12:19:10] [pool-4-thread-1 INFO] CustomSkinLoader 14.11

[2022-07-27 20:34:37] [Render thread INFO] CustomSkinLoader 14.14-SNAPSHOT-325

[2024-03-01 16:05:20] [Render thread/INFO] [CustomSkinLoader Core]: CustomSkinLoader 14.19.1
```

Regexp:

```php
 ->setPattern("\[\d{4}(?:\-\d\d){2} (?:[0-9]{2}\:?){3}\] \[.*thread.*[ \/]INFO\] CustomSkinLoader " 

 ->setPattern("\[\d{4}(?:\-\d\d){2} (?:[0-9]{2}\:?){3}\] \[Render thread\/INFO\] \[CustomSkinLoader Core\]: CustomSkinLoader " 
```

**Comment by JulianVennen** [comment]
Hey, could you provide full example logs for the cases where these differ?
That way, I can add test cases for them as well.

**Comment by SerinaNya** [comment]
> Hey, could you provide full example logs for the cases where these differ? That way, I can add test cases for them as well.

Yeah, I have collected some log files. The origin name of all of the files are `CustomSkinLoader.log`.

[CustomSkinLoader (9).log](https://github.com/user-attachments/files/15845556/CustomSkinLoader.9.log)
[CustomSkinLoader (8).log](https://github.com/user-attachments/files/15845557/CustomSkinLoader.8.log)
[CustomSkinLoader (7).log](https://github.com/user-attachments/files/15845558/CustomSkinLoader.7.log)
[CustomSkinLoader (6).log](https://github.com/user-attachments/files/15845559/CustomSkinLoader.6.log)
[CustomSkinLoader (2).log](https://github.com/user-attachments/files/15845560/CustomSkinLoader.2.log)
[CustomSkinLoader (5).log](https://github.com/user-attachments/files/15845561/CustomSkinLoader.5.log)
[CustomSkinLoader (4).log](https://github.com/user-attachments/files/15845562/CustomSkinLoader.4.log)
[CustomSkinLoader (3).log](https://github.com/user-attachments/files/15845563/CustomSkinLoader.3.log)
[CustomSkinLoader (1).log](https://github.com/user-attachments/files/15845564/CustomSkinLoader.1.log)

**Comment by JulianVennen** [comment]
File 1 and 5 are identical. 2, 6 and 9 are the same version (although started at different times).

**Comment by SerinaNya** [comment]
> File 1 and 5 are identical. 2, 6 and 9 are the same version (although started at different times).

Hers's all the log file I can provide at this time...

In my opinion it is enough for this issue. 🤗
