### ISSUE TITLE
NeoForge client logs detected as server log

### ISSUE THREAD

**Issue by Poopooracoocoo** [aternosorg/codex-minecraft#92]
https://mclo.gs/pUSbHQx NeoForge client latest.log
https://mclo.gs/2hygZu6 NeoForge client debug.log

**Comment by pavog** [comment]
mclogs was still on codex-minecraft 3.2.0.
I fixed this with the update from 3.2.0 to 3.5.0.
https://github.com/aternosorg/mclogs/pull/137

**Comment by Poopooracoocoo** [comment]
While the latest.log is detected correctly, the debug.log is not.

**Comment by Poopooracoocoo** [comment]
Sorry to dogpile but here's another one that should be detected as a NeoForge server: https://mclo.gs/Dslya7E

**Comment by JulianVennen** [comment]
Unfortunately, there do not appear to be any messages in that debug log that we could use to detect whether this is a client or server log.
I don't really see any reason for us to detect debug logs specifically either.
